INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Order Details','stg','OrderDetails')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Orders','stg','Orders')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Products','stg','Products')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Categories','stg','Categories')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Customers','stg','Customers')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Shippers','stg','Shippers')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Suppliers','stg','Suppliers')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Employees','stg','Employees')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','CustomerCustomerDemo','stg','CustomerCustomerDemo')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','CustomerDemographics','stg','CustomerDemographics')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Region','stg','Region')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','Territories','stg','Territories')
INSERT INTO audit.WorldWideTableList (SourceDbSchema, SourceTableName, StgDbSchema,StgTableName) VALUES ('dbo','EmployeeTerritories','stg','EmployeeTerritories')